systems:
  -
    name: MyClient Conference Room
    id: 3
    description: System description.
    connection: 192.168.1.2
    includes: # Automatically glob files from 'include' folder
      - include2/**/*.axi
    excluded_files:
      - include/excluded_file.axi
    touch_panels: # Look in 'touch_panel' folder
      -
        path: Admin iPad.TP4
        dps: '10001:1:0'
      - 
        path: Conference Room Table.TP5
        dps:
          - '10002:1:0'
          - '10003:1:0'
    ir: # Look in 'ir' folder
      -
        path: Comcast,Comcast,xfinity,Unknown,1.irl
        dps: '5001:1:0'
      -
        path: LG,LG,Unknown,Unknown,1.irl
        dps:
          - '5001:2:0'
          - '5001:3:0'
